include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
