name: request_placeholder
description: Validation of requests to JSONPlaceholder - Free Fake REST API with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.0.2+1
  go_router: ^11.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.4
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true
