name: request_placeholder
description: Validation of requests to JSONPlaceholder - Free Fake REST API with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  logger:
  go_router:
  freezed_annotation:
  json_annotation:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
  riverpod_generator:
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.0


flutter:
  uses-material-design: true
